-- Table: public.modifiedtracks

-- DROP TABLE public.modifiedtracks;

CREATE TABLE public.modifiedtracks
(
    "MODIFIEDTRACKID" serial,
    "UNMODIFIEDTRACKID" integer NOT NULL,
    "MODIFIEDBYUSERID" integer NOT NULL,
    "TRACKLINK" text COLLATE pg_catalog."default",
    "DATEMODIFIED" date,
    "INGESTEDBYMODEL" boolean,
    CONSTRAINT modifiedtracks_pk PRIMARY KEY ("MODIFIEDTRACKID"),
    CONSTRAINT "MODIFIEDTRACKS_UNMODIFIEDTRACKS_FK" FOREIGN KEY ("UNMODIFIEDTRACKID")
        REFERENCES public.unmodifiedtracks ("UNMODIFIEDTRACKID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "MODIFIEDTRACKS_USERS_FK" FOREIGN KEY ("MODIFIEDBYUSERID")
        REFERENCES public.users ("USERID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public.modifiedtracks
    OWNER to admin;
-- Index: fki_MODIFIEDTRACKS_UNMODIFIEDTRACKS_FK

-- DROP INDEX public."fki_MODIFIEDTRACKS_UNMODIFIEDTRACKS_FK";

CREATE INDEX "fki_MODIFIEDTRACKS_UNMODIFIEDTRACKS_FK"
    ON public.modifiedtracks USING btree
    ("UNMODIFIEDTRACKID" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: fki_MODIFIEDTRACKS_USERS_FK

-- DROP INDEX public."fki_MODIFIEDTRACKS_USERS_FK";

CREATE INDEX "fki_MODIFIEDTRACKS_USERS_FK"
    ON public.modifiedtracks USING btree
    ("MODIFIEDBYUSERID" ASC NULLS LAST)
    TABLESPACE pg_default;