-- Table: public.REQUESTEDTRACKMODIFICATIONS

-- DROP TABLE public.REQUESTEDTRACKMODIFICATIONS;

CREATE TABLE public.REQUESTEDTRACKMODIFICATIONS
(
    "REQUESTEDTRACKMODIFICATIONID" integer NOT NULL,
    "UNMODIFIEDTRACKID" integer NOT NULL,
    "MODIFYINGUSERID" integer NOT NULL,
    "JSONCONFIG" text COLLATE pg_catalog."default",
    "DATEMODIFIED" date,
    CONSTRAINT requestedtrackmodifications_pk PRIMARY KEY ("REQUESTEDTRACKMODIFICATIONID"),
    CONSTRAINT "REQUESTEDTRACKMODIFICATIONS_UNMODIFIEDTRACKS_FK" FOREIGN KEY ("UNMODIFIEDTRACKID")
        REFERENCES public.unmodifiedtracks ("UNMODIFIEDTRACKID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "REQUESTEDTRACKMODIFICATIONS_USERS_FK" FOREIGN KEY ("MODIFYINGUSERID")
        REFERENCES public.users ("USERID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public.REQUESTEDTRACKMODIFICATIONS
    OWNER to admin;
-- Index: fki_REQUESTEDTRACKMODIFICATIONS_UNMODIFIEDTRACKS_FK

-- DROP INDEX public."fki_REQUESTEDTRACKMODIFICATIONS_UNMODIFIEDTRACKS_FK";

CREATE INDEX "fki_REQUESTEDTRACKMODIFICATIONS_UNMODIFIEDTRACKS_FK"
    ON public.REQUESTEDTRACKMODIFICATIONS USING btree
    ("UNMODIFIEDTRACKID" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: fki_REQUESTEDTRACKMODIFICATIONS_USERS_FK

-- DROP INDEX public."fki_REQUESTEDTRACKMODIFICATIONS_USERS_FK";

CREATE INDEX "fki_REQUESTEDTRACKMODIFICATIONS_USERS_FK"
    ON public.REQUESTEDTRACKMODIFICATIONS USING btree
    ("MODIFYINGUSERID" ASC NULLS LAST)
    TABLESPACE pg_default;